### PR TITLE
Add Dedicated MacOS/Bluestacks Guide

### PR DESCRIPTION
**Pull request by maphe**
Hi, I tried playing with your tool on MacOS and Mac does not make it easy. Your tool itself works great, taking the screenshots is something else tho. First of all Bluestacks is the only emulator that works and it works differently than on Windows.

I thought I'd write down all the shenanigans I had to go through to get a screenshot imported correctly. I'm sure most users have a PC at home but it might be useful to some nonetheless.

### CODE REVIEW

**Comment by fribbels** [comment]
Yeah Mac and Bluestacks in general have been pretty problematic with screenshots. I appreciate you listing out all the Mac steps though. Could you verify that fullscreening Bluestacks and then taking screenshots with the hotkey doesn't generate 1600x900 pics for you? That worked on the two mac machines I tested.

**Comment by maphe** [comment]
Are you referring to the MacOS hotkey? I wasn't able to configure/use a shortcut in Bluestacks directly. When I use the MacOS shortcut (Cmd+shift+3) it takes the whole screen including black areas on top and bottom of the game.

**Comment by fribbels** [comment]
On my mac I was able to use the default "Take screenshot" hotkey in the bluestacks settings under hamburger icon -> settings -> shortcut keys, which I think was Cmd + Shift + S. Separately there was also a menu option with "Take screenshot" that worked too

> I wasn't able to configure/use a shortcut in Bluestacks directly
Oh interesting.. bluestacks is full of fun

**Comment by maphe** [comment]
I can't manage to find a way to set a shortcut (I'm not sure where you found the hamburger menu in Settings), but using the menu option you're right the screenshot is indeed 1600x900 when taken in full screen mode, which makes the process already easier (just missing the keyboard piece).

I'll update the PR during the weekend. Thanks for the tip.

**Comment by fribbels** [comment]
Some screenshots to illustrate what I meant:

https://i.imgur.com/IMEwVNj.png
https://i.imgur.com/DYQ8Yyo.png
https://i.imgur.com/p9zqrHW.png

**Comment by maphe** [comment]
My Bluestacks UI on Mac does not look like this at all, there's no hamburger menu, no right sidebar, nothing.

However I finally found a way to set up a custom shortcut for taking screenshots. So I think I have a pretty straightforward process. I'll update the PR as soon as I can.

**Pull request merged**
