### PR TITLE
Translate to Korean

### PR DESCRIPTION
**Pull request by jkaae93**

### CODE REVIEW

**Comment by fribbels** [comment]
Hey, what's your discord name, and are you in the server yet?

**Comment by jkaae93** [comment]
> Hey, what's your discord name, and are you in the server yet?

Discord 가애KAAE#8818.
I'm not join in your discord. have problem?
Could you let me know if there is a procedure I have to do?

**Comment by fribbels** [comment]
Join in here first, https://discord.gg/rDmB4Un7qg, there are a bunch of different people working on different translations, and we have someone doing korean as well. Just want to make sure everyone's on the same page and not duplicating work.

**Comment by jkaae93** [comment]
> Join in here first, https://discord.gg/rDmB4Un7qg, there are a bunch of different people working on different translations, and we have someone doing korean as well. Just want to make sure everyone's on the same page and not duplicating work.

Oh sorry. I will joined now.

**Pull request closed without merging**
